### ISSUE TITLE
Problem using 2 servos

### ISSUE THREAD

**Issue by grangep** [nanpy/nanpy#29]
Environment is a Raspberry Pi and a Dawn Robotics Co-op board, which is effectively an Arduino Uno.
Code is

``` python
#!/usr/bin/env python
from nanpy import ArduinoApi
from nanpy import SerialManager
from nanpy import Servo
from time import sleep
import logging
logging.basicConfig(level=logging.DEBUG)
SERVO_PAN = 9
SERVO_TILT = 10
connection = SerialManager(device='/dev/ttyS0')
panservo=Servo(SERVO_PAN)
tiltservo=Servo(SERVO_TILT)
sleep(2)
panservo.write(80)
sleep(1)
tiltservo.write(80)
sleep(5)
panservo.write(90)
sleep(1)
tiltservo.write(90)
sleep(5)
print"Finished"
```

The first time I run the code after power up or pressing the reset button on the co-op board everything works as expected, log file is:-

```
DEBUG:nanpy.serialmanager:opening port:/dev/ttyS0 [115200 baud]
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'new\x00'
DEBUG:nanpy.serialmanager:sending:'9\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'new\x00'
DEBUG:nanpy.serialmanager:sending:'10\x00'
DEBUG:nanpy.serialmanager:received:'1\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'80\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'80\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'90\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'90\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'remove\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'remove\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
Finished
```

The second time I run the code the servos act more hesitantly, and the tilt servo jitters up and down, but stops jittering when the servos return to the 90 position. The log is:-

```
DEBUG:nanpy.serialmanager:opening port:/dev/ttyS0 [115200 baud]
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'new\x00'
DEBUG:nanpy.serialmanager:sending:'9\x00'
DEBUG:nanpy.serialmanager:received:'1\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'new\x00'
DEBUG:nanpy.serialmanager:sending:'10\x00'
DEBUG:nanpy.serialmanager:received:'2\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'80\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'2\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'80\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'90\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'2\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'write\x00'
DEBUG:nanpy.serialmanager:sending:'90\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'remove\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'2\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'remove\x00'
DEBUG:nanpy.serialmanager:received:'0\r\n'
Finished
```

The log is pretty much identical except that the servos now seem to be 1 & 2 instead of 0 & 1

The third time I run the code the tilt servo jumps a little then we get a serial timeout. The log is:-

```
DEBUG:nanpy.serialmanager:opening port:/dev/ttyS0 [115200 baud]
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'new\x00'
DEBUG:nanpy.serialmanager:sending:'9\x00'
DEBUG:nanpy.serialmanager:received:''
Traceback (most recent call last):
  File "./Test4.py", line 11, in <module>
    panservo=Servo(SERVO_PAN)
  File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9.1-py2.7.egg/nanpy/servo.py", line 8, in __init__
    self.id = self.call('new', pin)
  File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9.1-py2.7.egg/nanpy/arduinoboard.py", line 148, in call
    return _call(self.namespace, self.id, args, self.connection)
  File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9.1-py2.7.egg/nanpy/arduinoboard.py", line 46, in _call
    ret = return_value(connection)
  File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9.1-py2.7.egg/nanpy/arduinoboard.py", line 18, in return_value
    return serial_manager.readline().replace('\r\n', '')
  File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9.1-py2.7.egg/nanpy/serialmanager.py", line 96, in readline
    raise SerialManagerError('Serial timeout!')
nanpy.serialmanager.SerialManagerError: Serial timeout!
```

The equivalent code runs ok on Pymata.

**Comment by balintszabo96** [comment]
**Hi, when I try to run**
nanpy/examples/reset.py
**I get the following response:**
uptime: 513.648 sec
soft reset
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/memo.py", line 18, in __call__
KeyError: (<nanpy.arduinotree.ArduinoTree object at 0x7688eb30>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reset.py", line 20, in <module>
    reset_demo()
  File "reset.py", line 16, in reset_demo
    a.soft_reset()
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/arduinotree.py", line 130, in soft_reset
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/memo.py", line 20, in __call__
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/arduinotree.py", line 81, in watchdog
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/classinfo.py", line 26, in getinstance
nanpy.classinfo.FirmwareMissingFeatureError: <class 'nanpy.watchdog.Watchdog'> ['Watchdog'] is missing from firmware!
**I am only trying to run one servo. If I physically reset the Arduino from the button, the servo.py program from the repository runs fine, but the next time the servo jitters.
Please help me out.**
