### ISSUE TITLE
serialmanager Serial timeout! with multiple (4) servos

### ISSUE THREAD

**Issue by s-purch** [nanpy/nanpy#69]
Hi,
I am using nanpy with a raspberry pi to communicate with an arduino uno to run 4 motors and a few sensors and I am getting this error after varying amounts of time (a few seconds to a few minutes):

Traceback (most recent call last):
  File "/home/pi/TLB1 Control Program.py", line 278, in <module>
    motor3.writeMicroseconds(motor3Speed)
  File "/usr/local/lib/python3.2/dist-packages/nanpy/arduinoboard.py", line 68, in wrapper
    return _call(self.namespace, self.id, call_pars, connection=connection)
  File "/usr/local/lib/python3.2/dist-packages/nanpy/arduinoboard.py", line 46, in _call
    ret = return_value(connection)
  File "/usr/local/lib/python3.2/dist-packages/nanpy/arduinoboard.py", line 18, in return_value
    return serial_manager.readline().replace('\r\n', '')
  File "/usr/local/lib/python3.2/dist-packages/nanpy/serialmanager.py", line 96, in readline
    raise SerialManagerError('Serial timeout!')
nanpy.serialmanager.SerialManagerError: Serial timeout!

The logging with debug looks like this up to the error:

DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'2\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'3\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'0\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b'0\r\n'
DEBUG:nanpy.serialmanager:sending:'Servo\x00'
DEBUG:nanpy.serialmanager:sending:'2\x00'
DEBUG:nanpy.serialmanager:sending:'1\x00'
DEBUG:nanpy.serialmanager:sending:'writeMicroseconds\x00'
DEBUG:nanpy.serialmanager:sending:'1500\x00'
DEBUG:nanpy.serialmanager:received:b''
Traceback (most recent call last):
  File "/home/pi/TLB1 Control Program.py", line 278, in <module>
    motor3.writeMicroseconds(motor3Speed)
  File "/usr/local/lib/python3.2/dist-packages/nanpy/arduinoboard.py", line 68, in wrapper
....

it always fails with this received: b''

attached is the code I am running

I have been testing it without the motors.

[TLB1 Control Program.txt](https://github.com/nanpy/nanpy/files/227052/TLB1.Control.Program.txt)

Any help would be appreciated!

**Comment by ponty** [comment]
Try to create a small test program and locate the problem. Remove pygame, A.delay(),...

This may be a RAM problem, try with less motors.
