### ISSUE TITLE
Using Servos

### ISSUE THREAD

**Issue by RyTheHackerGuy** [nanpy/nanpy#92]
I cant figure out the Servo usage, this is the shell error:

```
Traceback (most recent call last):
  File "/home/pi/Desktop/nanpy/RobotCode.py", line 28, in <module>
    servoA = Servo(2)
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/servo.py", line 9, in __init__
    self.id = self.call('new', pin)
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/arduinoboard.py", line 150, in call
    return _call(self.namespace, self.id, args, self.connection)
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/arduinoboard.py", line 47, in _call
    ret = return_value(connection)
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/arduinoboard.py", line 18, in return_value
    return serial_manager.readline().replace('\r\n', '')
  File "/usr/local/lib/python3.4/dist-packages/nanpy-0.9.6-py3.4.egg/nanpy/serialmanager.py", line 101, in readline
    raise SerialManagerError('Serial timeout!')
nanpy.serialmanager.SerialManagerError: Serial timeout!
```

here is my code:
...
from nanpy import (ArduinoApi, SerialManager)
import pygame
from nanpy import Servo
import time
pygame.init()

a=0
d=0

window = pygame.display.set_mode((800,600))

pygame.display.set_caption("Console")

try :
    connection = SerialManager()
    ard = ArduinoApi(connection = connection)
    run = True
except:
    print("Connection Failed!")

servoA = Servo(2)
servoD = Servo(4)
while run :
      for event in pygame.event.get():
                     keys = pygame.key.get_pressed()
           # if (event.type==pygame.KEYDOWN):

                     if keys[pygame.K_s] and keys[pygame.K_a]:
                            a=a-1
                            servoA.write(a)
                     elif keys[pygame.K_s] and keys[pygame.K_d]:
                            d=d-1
                            servoD.write(d)

                     elif keys[pygame.K_w]:
                            a=a+1
                            d=d+1
                            servoD.write(d)
                            servoA.write(a)

                     elif keys[pygame.K_s]:
                            a=a-1
                            d=d-1
                            servoD.write(d)
                            servoA.write(a)

                     elif keys[pygame.K_d]:

                            d=d+1
                            servoD.write(d)

                     elif keys[pygame.K_a]:
                            a=a+1
                            servoA.write(a)

                     elif keys[pygame.K_t]:
                            run=False

pygame.quit()

...

**Comment by dankozlowski** [comment]
Serial timeout means you likely didn't bootstrap the Arduino successfully.

**Comment by RyTheHackerGuy** [comment]
@dankozlowski What do I need to do to fix the Bootstrap?

**Comment by ponty** [comment]
Please read ISSUE_TEMPLATE.md.
Please remove Pygame from your code and make it simple.

**Comment by dankozlowski** [comment]
@RyTheHackerGuy I'd start by posting steps to reproduce.

**Comment by dankozlowski** [comment]
How did you bootstrap you Arduino?  Can you paste the output from the programmer?

**Comment by RyTheHackerGuy** [comment]
@ponty  pygame is for tracking the keys being pressed, I found it to be easier than using tkinter

but I'll get the logging in ASAP

**Comment by RyTheHackerGuy** [comment]
@dankozlowski I followed exactly as shown in this [video]( https://www.youtube.com/watch?v=QumIhvYtRKQ)  but I didnt adjust anything within the files, I left those as they were, (Im really sorry but) what do you mean by the programmer? I assume you mean the logged output mentioned by @ponty

**Comment by RyTheHackerGuy** [comment]
As I'm still very new to this, I kinda assumed that the 
```
 connection = SerialManager()
 ard = ArduinoApi(connection = connection)
```
  made the bootstrap  (I have never worked with a Pi or Arduino before this project so I apologize for being such a noob )

**Comment by ponty** [comment]
follow the README: "You can now edit Nanpy/cfg.h generated file to configure your Nanpy firmware, selecting the features you want to include and the baud rate."

Edit the cfg.h file and enable Servo.

**Comment by RyTheHackerGuy** [comment]
@ponty I think you saved me bro

**Comment by RyTheHackerGuy** [comment]
oh and just as a clarifying question, 
'servoOne =Servo(1)'
binds to the digital output right?
